[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"
[project]
name = "local-lakehouse"
version = "0.1.0"
description = "A local lakehouse implementation for learning dbms and storage systems"
requires-python = ">=3.13"

dependencies=[
    "duckdb",
    "pyarrow",
]
[project.optional-dependencies]
dev =[
    "pytest",
]
